# Site
name: "Minik Damla"
title: "Minik Damla"
description: "Minik Damla Avrupa standartları ve Türk kültürünün ortaya çıkarttığı tüm eğitim yöntemlerinin Montessori, Reggio ve Emilia, Scamber, Orff gibi metotların ülkemizde ki öncüsüdür."
meta_description: "Minik Damla"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'iletisim@damlayayinevi.com.tr'
google_analytics: 'UA-53710816-12'
disqus: 'demowebsite'
twitter: https://twitter.com/damlayayinevi
facebook: https://www.facebook.com/DamlaYayinevi/
instagram: https://www.instagram.com/damlayayinevi/
youtube: https://www.youtube.com/user/damlayayinevi
permalink: "/:title"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

gem:
    -jekyll-sitemap